---
version: '2'
networks:
  kafka_Network:
    name: kafka_Network
    
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: zookeeper
    networks: 
      - kafka_Network
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181 
      ZOOKEEPER_TICK_TIME: 2000
  broker1:
    image: confluentinc/cp-kafka
    hostname: broker1
    container_name: broker1
    networks: 
      - kafka_Network
    depends_on:
      - zookeeper
    ports:
      - 9093:9093
    expose:
      - 9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:9093
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
  broker2:
    image: confluentinc/cp-kafka
    hostname: broker2
    container_name: broker2
    networks: 
      - kafka_Network
    depends_on:
      - zookeeper
    ports:
      - 9094:9093
    expose:
      - 9094
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:9093
  broker3:
    image: confluentinc/cp-kafka
    hostname: broker3
    container_name: broker3
    networks: 
      - kafka_Network
    depends_on:
      - zookeeper
    ports:
      - 9095:9093
    expose:
      - 9095
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:9093